name: Test Action

on:
  workflow_dispatch:

jobs:
  Commit:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Setup test commit
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git pull origin main
          date > time.txt
          git add time.txt
          git commit -m "fix: ğŸ° Oh my fur and whiskers! I'm late, I'm late, I'm late! ğŸ‡"
          git push origin main

  Test:
    needs: Commit
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: matteo4diani/poetry-semantic-release@main
        name: Test Semantic Release
        id: test-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}
    outputs:
      released: ${{ steps.test-release.outputs.released }}

  Dispatch:
    needs: Test
    if: github.ref == 'refs/heads/main' && needs.Test.outputs.released == 'true'
    permissions: write-all
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/github-script@v6
        name: Dispatch Release
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'matteo4diani',
              repo: 'poetry-semantic-release',
              workflow_id: 'release.yml',
              ref: 'main'
            })